#!/bin/bash
if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit 1
fi
mkdir $1 && cd $1 
mkdir css && cd css && touch styles.css
cd ..
mkdir assets && cd assets && touch logo.sv && touch photo.jpg
cd ..
mkdir js && cd js && touch scripts.js
cd ..
touch index.html


#this is for the medium and large project

